<#
.SYNOPSIS
    Phoenix SDR Controller Build Script
    
.DESCRIPTION
    Builds the project with automatic version management.
    Build number auto-increments on every build.
    
.PARAMETER Release
    Build with optimizations (Release mode). Default is Debug.
    
.PARAMETER Clean
    Delete build directory before building.
    
.PARAMETER Increment
    Increment version: patch, minor, or major.
    Resets build number to 0.
    
.EXAMPLE
    .\build.ps1                      # Debug build, increments BUILD
    .\build.ps1 -Release             # Optimized build
    .\build.ps1 -Clean               # Delete build/ directory first
    .\build.ps1 -Increment patch     # 0.3.0 → 0.3.1, resets BUILD to 0
#>

param(
    [switch]$Release,
    [switch]$Clean,
    [ValidateSet("patch", "minor", "major")]
    [string]$Increment
)

$ErrorActionPreference = "Stop"

# Paths
$ProjectRoot = $PSScriptRoot
$VersionFile = Join-Path $ProjectRoot "include\version.h"
$BuildDir = Join-Path $ProjectRoot "build"

# Get git info
function Get-GitInfo {
    $commit = "0000000"
    $dirty = $false
    
    try {
        $commit = (git -C $ProjectRoot rev-parse --short=7 HEAD 2>$null).Trim()
        $status = git -C $ProjectRoot status --porcelain 2>$null
        $dirty = [bool]$status
    } catch {}
    
    return @{
        Commit = $commit
        Dirty = $dirty
    }
}

# Read current version from version.h
function Get-Version {
    if (-not (Test-Path $VersionFile)) {
        return @{ Major = 0; Minor = 1; Patch = 0; Build = 0 }
    }
    
    $content = Get-Content $VersionFile -Raw
    
    $major = [regex]::Match($content, '#define VERSION_MAJOR\s+(\d+)').Groups[1].Value
    $minor = [regex]::Match($content, '#define VERSION_MINOR\s+(\d+)').Groups[1].Value
    $patch = [regex]::Match($content, '#define VERSION_PATCH\s+(\d+)').Groups[1].Value
    $build = [regex]::Match($content, '#define VERSION_BUILD\s+(\d+)').Groups[1].Value
    
    return @{
        Major = [int]$major
        Minor = [int]$minor
        Patch = [int]$patch
        Build = [int]$build
    }
}

# Write version to version.h
function Set-Version {
    param($Major, $Minor, $Patch, $Build)
    
    $git = Get-GitInfo
    $versionString = "$Major.$Minor.$Patch"
    $versionFull = "$Major.$Minor.$Patch+$Build.$($git.Commit)"
    if ($git.Dirty) {
        $versionFull += "-dirty"
    }
    $dirtyStr = if ($git.Dirty) { "true" } else { "false" }
    
    $content = @"
/*
 * version.h - Phoenix SDR Controller Version Information
 * 
 * This file is auto-generated by build.ps1 - do not edit manually
 * 
 * Version format: MAJOR.MINOR.PATCH+BUILD.COMMIT[-dirty]
 * Example: 0.3.0+67.abc1234 or 0.3.0+67.abc1234-dirty
 */

#ifndef VERSION_H
#define VERSION_H

#define VERSION_MAJOR       $Major
#define VERSION_MINOR       $Minor
#define VERSION_PATCH       $Patch
#define VERSION_BUILD       $Build

/* Version string for display: "0.3.0" */
#define VERSION_STRING      "$versionString"

/* Full version with build info: "0.3.0+67.abc1234" */
#define VERSION_FULL        "$versionFull"

/* Git commit hash (short) */
#define VERSION_COMMIT      "$($git.Commit)"

/* true if there were uncommitted changes during build */
#define VERSION_DIRTY       $dirtyStr

#endif /* VERSION_H */
"@
    
    Set-Content -Path $VersionFile -Value $content -NoNewline
    return $versionFull
}

# Clean build directory
function Clean-BuildDir {
    Write-Host "Cleaning build directory..." -ForegroundColor Yellow
    if (Test-Path $BuildDir) {
        Remove-Item -Recurse -Force $BuildDir
    }
    Write-Host "Clean complete." -ForegroundColor Green
}

# Main logic

# Handle -Clean
if ($Clean) {
    Clean-BuildDir
}

# Handle -Increment
if ($Increment) {
    $v = Get-Version
    $oldVersion = "$($v.Major).$($v.Minor).$($v.Patch)"
    
    switch ($Increment) {
        "major" {
            $v.Major++
            $v.Minor = 0
            $v.Patch = 0
        }
        "minor" {
            $v.Minor++
            $v.Patch = 0
        }
        "patch" {
            $v.Patch++
        }
    }
    $v.Build = 0  # Reset build number
    
    $newVersion = Set-Version -Major $v.Major -Minor $v.Minor -Patch $v.Patch -Build $v.Build
    Write-Host "Version incremented: $oldVersion -> $newVersion" -ForegroundColor Green
    exit 0
}

# Build
Write-Host "`n=== Building Phoenix SDR Controller ===" -ForegroundColor Cyan

# Increment build number
$v = Get-Version
$v.Build++
$fullVersion = Set-Version -Major $v.Major -Minor $v.Minor -Patch $v.Patch -Build $v.Build
Write-Host "Version: $fullVersion" -ForegroundColor Cyan

# Configure if needed
if (-not (Test-Path (Join-Path $BuildDir "CMakeCache.txt"))) {
    Write-Host "Configuring CMake..." -ForegroundColor Yellow
    cmake -B $BuildDir -S $ProjectRoot
    if ($LASTEXITCODE -ne 0) { throw "CMake configure failed" }
}

# Build
$config = if ($Release) { "Release" } else { "Debug" }
Write-Host "Building $config..." -ForegroundColor Yellow
cmake --build $BuildDir --config $config
if ($LASTEXITCODE -ne 0) { throw "Build failed" }

Write-Host "`nBuild successful: $fullVersion ($config)" -ForegroundColor Green
