<#
.SYNOPSIS
    Phoenix SDR Controller Release Deployment Script
    
.DESCRIPTION
    Creates a release by updating version, committing, tagging, and pushing.
    The tag push triggers GitHub Actions to build and publish the release.
    
.PARAMETER Patch
    Increment patch version (0.3.0 → 0.3.1)
    
.PARAMETER Minor
    Increment minor version (0.3.0 → 0.4.0)
    
.PARAMETER Major
    Increment major version (0.3.0 → 1.0.0)
    
.PARAMETER DryRun
    Preview what would happen without making changes
    
.EXAMPLE
    .\deploy_release.ps1             # Increment BUILD only
    .\deploy_release.ps1 -Patch      # 0.3.0 → 0.3.1 (bug fix release)
    .\deploy_release.ps1 -Minor      # 0.3.0 → 0.4.0 (feature release)
    .\deploy_release.ps1 -Major      # 0.3.0 → 1.0.0 (breaking changes)
    .\deploy_release.ps1 -DryRun     # Preview without pushing
#>

param(
    [switch]$Patch,
    [switch]$Minor,
    [switch]$Major,
    [switch]$DryRun
)

$ErrorActionPreference = "Stop"

# Paths
$ProjectRoot = $PSScriptRoot
$VersionFile = Join-Path $ProjectRoot "include\version.h"

# Get git info
function Get-GitInfo {
    $commit = "0000000"
    $dirty = $false
    
    try {
        $commit = (git -C $ProjectRoot rev-parse --short=7 HEAD 2>$null).Trim()
        $status = git -C $ProjectRoot status --porcelain 2>$null
        $dirty = [bool]$status
    } catch {}
    
    return @{
        Commit = $commit
        Dirty = $dirty
    }
}

# Read current version from version.h
function Get-Version {
    $content = Get-Content $VersionFile -Raw
    
    $major = [regex]::Match($content, '#define VERSION_MAJOR\s+(\d+)').Groups[1].Value
    $minor = [regex]::Match($content, '#define VERSION_MINOR\s+(\d+)').Groups[1].Value
    $patch = [regex]::Match($content, '#define VERSION_PATCH\s+(\d+)').Groups[1].Value
    $build = [regex]::Match($content, '#define VERSION_BUILD\s+(\d+)').Groups[1].Value
    
    return @{
        Major = [int]$major
        Minor = [int]$minor
        Patch = [int]$patch
        Build = [int]$build
    }
}

# Write version to version.h
function Set-Version {
    param($Major, $Minor, $Patch, $Build, $Commit)
    
    $versionString = "$Major.$Minor.$Patch"
    $versionFull = "$Major.$Minor.$Patch+$Build.$Commit"
    
    $content = @"
/*
 * version.h - Phoenix SDR Controller Version Information
 * 
 * This file is auto-generated by deploy_release.ps1 - do not edit manually
 * 
 * Version format: MAJOR.MINOR.PATCH+BUILD.COMMIT[-dirty]
 * Example: 0.3.0+67.abc1234 or 0.3.0+67.abc1234-dirty
 */

#ifndef VERSION_H
#define VERSION_H

#define VERSION_MAJOR       $Major
#define VERSION_MINOR       $Minor
#define VERSION_PATCH       $Patch
#define VERSION_BUILD       $Build

/* Version string for display: "0.3.0" */
#define VERSION_STRING      "$versionString"

/* Full version with build info: "0.3.0+67.abc1234" */
#define VERSION_FULL        "$versionFull"

/* Git commit hash (short) */
#define VERSION_COMMIT      "$Commit"

/* true if there were uncommitted changes during build */
#define VERSION_DIRTY       false

#endif /* VERSION_H */
"@
    
    Set-Content -Path $VersionFile -Value $content -NoNewline
    return @{
        String = $versionString
        Full = $versionFull
    }
}

# Main

Write-Host "`n=== Phoenix SDR Controller Release ===" -ForegroundColor Cyan

# 1. Validate - Check for uncommitted changes
$git = Get-GitInfo
if ($git.Dirty) {
    Write-Host "ERROR: You have uncommitted changes!" -ForegroundColor Red
    git -C $ProjectRoot status --short
    throw "Commit or stash changes before deploying a release"
}

# 2. Calculate new version
$v = Get-Version
$oldVersion = "$($v.Major).$($v.Minor).$($v.Patch)"

if ($Major) {
    $v.Major++
    $v.Minor = 0
    $v.Patch = 0
    $v.Build = 1
} elseif ($Minor) {
    $v.Minor++
    $v.Patch = 0
    $v.Build = 1
} elseif ($Patch) {
    $v.Patch++
    $v.Build = 1
} else {
    $v.Build++
}

$newVersionStr = "$($v.Major).$($v.Minor).$($v.Patch)"
$tagName = "v$($v.Major).$($v.Minor).$($v.Patch)+$($v.Build).$($git.Commit)"

Write-Host "Current version: $oldVersion" -ForegroundColor Gray
Write-Host "New version:     $newVersionStr (build $($v.Build))" -ForegroundColor Green
Write-Host "Tag:             $tagName" -ForegroundColor Cyan

if ($DryRun) {
    Write-Host "`n[DRY RUN] Would perform the following:" -ForegroundColor Yellow
    Write-Host "  1. Update include/version.h"
    Write-Host "  2. Commit: 'v$newVersionStr build $($v.Build)'"
    Write-Host "  3. Amend with updated git hash"
    Write-Host "  4. Push to origin"
    Write-Host "  5. Create and push tag: $tagName"
    exit 0
}

# 3. Update version.h (first pass - with old commit)
Write-Host "`nUpdating version.h..." -ForegroundColor Yellow
$verInfo = Set-Version -Major $v.Major -Minor $v.Minor -Patch $v.Patch -Build $v.Build -Commit $git.Commit

# 4. Commit
Write-Host "Committing..." -ForegroundColor Yellow
git -C $ProjectRoot add $VersionFile
git -C $ProjectRoot commit -m "v$newVersionStr build $($v.Build)"
if ($LASTEXITCODE -ne 0) { throw "Git commit failed" }

# 5. Amend with correct git hash
$newGit = Get-GitInfo
$verInfo = Set-Version -Major $v.Major -Minor $v.Minor -Patch $v.Patch -Build $v.Build -Commit $newGit.Commit
$tagName = "v$($v.Major).$($v.Minor).$($v.Patch)+$($v.Build).$($newGit.Commit)"

git -C $ProjectRoot add $VersionFile
git -C $ProjectRoot commit --amend --no-edit
if ($LASTEXITCODE -ne 0) { throw "Git amend failed" }

# 6. Push to origin
Write-Host "Pushing to origin..." -ForegroundColor Yellow
git -C $ProjectRoot push origin main
if ($LASTEXITCODE -ne 0) { throw "Git push failed" }

# 7. Create and push tag
Write-Host "Creating tag $tagName..." -ForegroundColor Yellow
git -C $ProjectRoot tag -a $tagName -m "Release $newVersionStr build $($v.Build)"
if ($LASTEXITCODE -ne 0) { throw "Git tag failed" }

git -C $ProjectRoot push origin $tagName
if ($LASTEXITCODE -ne 0) { throw "Git tag push failed" }

Write-Host "`n=== Release Complete ===" -ForegroundColor Green
Write-Host "Version: $($verInfo.Full)" -ForegroundColor Cyan
Write-Host "Tag:     $tagName" -ForegroundColor Cyan
Write-Host "`nGitHub Actions will now build and publish the release." -ForegroundColor Gray
Write-Host "Check: https://github.com/Alex-Pennington/phoenix_sdr_controller/actions" -ForegroundColor Gray
