name: "Feature Request"
description: "Propose a new feature or enhancement to existing functionality."
title: "FEATURE: [Brief description of the feature]"
labels: ["enhancement", "needs triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        # Feature Request
        Thank you for contributing to the project. Please provide enough detail for the dev team to evaluate and prioritize this request.

  - type: textarea
    id: problem-statement
    attributes:
      label: "Problem Statement"
      description: "What problem does this feature solve? What limitation or gap are you experiencing?"
      placeholder: "EXAMPLE: Currently there is no way to export configuration settings, so I have to manually reconfigure after updates."
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: "Proposed Solution"
      description: "Describe your ideal solution. How should this feature work?"
      placeholder: "EXAMPLE: Add an 'Export Config' button that saves settings to a JSON file."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives Considered"
      description: "Have you tried any workarounds? Are there other approaches that might solve this?"
      placeholder: "EXAMPLE: I tried manually copying the config file but it doesn't preserve all settings."
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: "Suggested Priority"
      description: "How critical is this feature to your workflow?"
      options:
        - "Nice to have - would improve experience"
        - "Important - significant workflow impact"
        - "Critical - blocking normal operations"
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: "Component Area"
      description: "Which part of the system does this feature relate to?"
      options:
        - "GUI / User Interface"
        - "SDR / Signal Processing"
        - "Modem / Demodulation"
        - "Configuration / Settings"
        - "Logging / Output"
        - "Documentation"
        - "Build / Installation"
        - "Other (specify below)"
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: "Use Case / Scenario"
      description: "Describe a real-world scenario where this feature would be used."
      placeholder: "EXAMPLE: During a MARS net, I need to quickly switch between modes without restarting the application."
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Any other information, mockups, or references that might help."
      placeholder: "Links to similar implementations, screenshots of desired behavior, etc."
    validations:
      required: false
