<#
.SYNOPSIS
    Phoenix SDR Controller Build Script
    
.DESCRIPTION
    Handles building, versioning, tagging, and releasing the Phoenix SDR Controller.
    
.PARAMETER Action
    build    - Build the project (default)
    release  - Increment patch, tag, and push (creates GitHub release via CI)
    major    - Increment major version, tag, and push
    minor    - Increment minor version, tag, and push
    patch    - Increment patch version, tag, and push
    clean    - Clean build directory
    
.EXAMPLE
    .\build.ps1              # Build only
    .\build.ps1 release      # Increment patch, tag, push (triggers release)
    .\build.ps1 major        # Increment major version
    .\build.ps1 minor        # Increment minor version
#>

param(
    [Parameter(Position=0)]
    [ValidateSet("build", "release", "major", "minor", "patch", "clean")]
    [string]$Action = "build"
)

$ErrorActionPreference = "Stop"

# Paths
$ProjectRoot = Split-Path -Parent $PSScriptRoot
$VersionFile = Join-Path $ProjectRoot "include\version.h"
$BuildDir = Join-Path $ProjectRoot "build"

# Read current version from version.h
function Get-Version {
    $content = Get-Content $VersionFile -Raw
    
    $major = [regex]::Match($content, '#define VERSION_MAJOR\s+(\d+)').Groups[1].Value
    $minor = [regex]::Match($content, '#define VERSION_MINOR\s+(\d+)').Groups[1].Value
    $patch = [regex]::Match($content, '#define VERSION_PATCH\s+(\d+)').Groups[1].Value
    $build = [regex]::Match($content, '#define VERSION_BUILD\s+(\d+)').Groups[1].Value
    
    return @{
        Major = [int]$major
        Minor = [int]$minor
        Patch = [int]$patch
        Build = [int]$build
    }
}

# Get git commit hash
function Get-GitCommit {
    try {
        $hash = git -C $ProjectRoot rev-parse --short HEAD 2>$null
        if ($LASTEXITCODE -eq 0 -and $hash) {
            return $hash.Trim()
        }
    } catch {}
    return "0000000"
}

# Write version to version.h
function Set-Version {
    param($Major, $Minor, $Patch, $Build)
    
    $commit = Get-GitCommit
    $versionString = "$Major.$Minor.$Patch"
    $versionFull = "$Major.$Minor.$Patch.$Build"
    $versionDetailed = "$Major.$Minor.$Patch.$Build-$commit"
    
    $content = @"
/*
 * version.h - Phoenix SDR Controller Version Information
 * 
 * This file is auto-generated by build.ps1 - do not edit manually
 */

#ifndef VERSION_H
#define VERSION_H

#define VERSION_MAJOR       $Major
#define VERSION_MINOR       $Minor
#define VERSION_PATCH       $Patch
#define VERSION_BUILD       $Build

/* Git commit hash (short) */
#define VERSION_COMMIT      "$commit"

/* Full version string for display */
#define VERSION_STRING      "$versionString"

/* Full version with build number (for internal/debug use) */
#define VERSION_FULL        "$versionFull"

/* Version with commit (for detailed info) */
#define VERSION_DETAILED    "$versionDetailed"

#endif /* VERSION_H */
"@
    
    Set-Content -Path $VersionFile -Value $content -NoNewline
    Write-Host "Updated version to $versionDetailed" -ForegroundColor Green
    
    return $versionString
}

# Increment build number
function Increment-Build {
    $v = Get-Version
    Set-Version -Major $v.Major -Minor $v.Minor -Patch $v.Patch -Build ($v.Build + 1)
}

# Build the project
function Build-Project {
    Write-Host "`n=== Building Phoenix SDR Controller ===" -ForegroundColor Cyan
    
    # Increment build number
    Increment-Build | Out-Null
    
    # Configure if needed
    if (-not (Test-Path (Join-Path $BuildDir "CMakeCache.txt"))) {
        Write-Host "Configuring CMake..." -ForegroundColor Yellow
        cmake -B $BuildDir -S $ProjectRoot
        if ($LASTEXITCODE -ne 0) { throw "CMake configure failed" }
    }
    
    # Build
    Write-Host "Building Release..." -ForegroundColor Yellow
    cmake --build $BuildDir --config Release
    if ($LASTEXITCODE -ne 0) { throw "Build failed" }
    
    $v = Get-Version
    Write-Host "`nBuild successful: v$($v.Major).$($v.Minor).$($v.Patch).$($v.Build)" -ForegroundColor Green
}

# Create release tag and push
function New-Release {
    param([string]$IncrementType = "patch")
    
    $v = Get-Version
    
    # Increment version
    switch ($IncrementType) {
        "major" {
            $v.Major++
            $v.Minor = 0
            $v.Patch = 0
        }
        "minor" {
            $v.Minor++
            $v.Patch = 0
        }
        "patch" {
            $v.Patch++
        }
    }
    $v.Build = 0  # Reset build number for release
    
    $versionString = Set-Version -Major $v.Major -Minor $v.Minor -Patch $v.Patch -Build $v.Build
    $tag = "v$versionString"
    
    Write-Host "`n=== Creating Release $tag ===" -ForegroundColor Cyan
    
    # Check for uncommitted changes
    $status = git -C $ProjectRoot status --porcelain
    if ($status) {
        # Commit version change
        Write-Host "Committing version update..." -ForegroundColor Yellow
        git -C $ProjectRoot add $VersionFile
        git -C $ProjectRoot commit -m "Release $tag"
        if ($LASTEXITCODE -ne 0) { throw "Git commit failed" }
    }
    
    # Create tag
    Write-Host "Creating tag $tag..." -ForegroundColor Yellow
    git -C $ProjectRoot tag -a $tag -m "Release $versionString"
    if ($LASTEXITCODE -ne 0) { throw "Git tag failed" }
    
    # Push
    Write-Host "Pushing to origin..." -ForegroundColor Yellow
    git -C $ProjectRoot push origin main
    if ($LASTEXITCODE -ne 0) { throw "Git push failed" }
    
    git -C $ProjectRoot push origin $tag
    if ($LASTEXITCODE -ne 0) { throw "Git tag push failed" }
    
    Write-Host "`nRelease $tag pushed! GitHub Actions will create the release." -ForegroundColor Green
    Write-Host "Check: https://github.com/Alex-Pennington/phoenix_sdr_controller/actions" -ForegroundColor Cyan
}

# Clean build directory
function Clean-Build {
    Write-Host "Cleaning build directory..." -ForegroundColor Yellow
    if (Test-Path $BuildDir) {
        Remove-Item -Recurse -Force $BuildDir
    }
    Write-Host "Clean complete." -ForegroundColor Green
}

# Main
switch ($Action) {
    "build" {
        Build-Project
    }
    "release" {
        Build-Project
        New-Release -IncrementType "patch"
    }
    "major" {
        Build-Project
        New-Release -IncrementType "major"
    }
    "minor" {
        Build-Project
        New-Release -IncrementType "minor"
    }
    "patch" {
        Build-Project
        New-Release -IncrementType "patch"
    }
    "clean" {
        Clean-Build
    }
}
