/*
 * version.h - Phoenix SDR Controller Version Information
 * 
 * This file is auto-generated by build.ps1 - do not edit manually
 * 
 * Version format: MAJOR.MINOR.PATCH+BUILD.COMMIT[-dirty]
 * Example: 0.3.0+67.abc1234 or 0.3.0+67.abc1234-dirty
 */

#ifndef VERSION_H
#define VERSION_H

#define VERSION_MAJOR       0
#define VERSION_MINOR       2
#define VERSION_PATCH       0
#define VERSION_BUILD       5

/* Version string for display: "0.3.0" */
#define VERSION_STRING      "0.2.0"

/* Full version with build info: "0.3.0+67.abc1234" */
#define VERSION_FULL        "0.2.0+5.853877d-dirty"

/* Git commit hash (short) */
#define VERSION_COMMIT      "853877d"

/* true if there were uncommitted changes during build */
#define VERSION_DIRTY       true

#endif /* VERSION_H */