/*
 * version.h - Phoenix SDR Controller Version Information
 * 
 * This file is auto-generated by build.ps1 - do not edit manually
 * 
 * Version format: MAJOR.MINOR.PATCH+BUILD.COMMIT[-dirty]
 * Example: 0.3.0+67.abc1234 or 0.3.0+67.abc1234-dirty
 */

#ifndef VERSION_H
#define VERSION_H

#define VERSION_MAJOR       0
#define VERSION_MINOR       6
#define VERSION_PATCH       1
#define VERSION_BUILD       7

/* Version string for display: "0.3.0" */
#define VERSION_STRING      "0.6.1"

/* Full version with build info: "0.3.0+67.abc1234" */
#define VERSION_FULL        "0.6.1+7.262eb43"

/* Git commit hash (short) */
#define VERSION_COMMIT      "262eb43"

/* true if there were uncommitted changes during build */
#define VERSION_DIRTY       false

#endif /* VERSION_H */