/*
 * version.h - Phoenix SDR Controller Version Information
 * 
 * This file is auto-generated by build.ps1 - do not edit manually
 */

#ifndef VERSION_H
#define VERSION_H

#define VERSION_MAJOR       0
#define VERSION_MINOR       1
#define VERSION_PATCH       0
#define VERSION_BUILD       1

/* Git commit hash (short) */
#define VERSION_COMMIT      "0000000"

/* Full version string for display */
#define VERSION_STRING      "0.1.0"

/* Full version with build number (for internal/debug use) */
#define VERSION_FULL        "0.1.0.1"

/* Version with commit (for detailed info) */
#define VERSION_DETAILED    "0.1.0.1-0000000"

#endif /* VERSION_H */
